baseURL = 'https://dustinturp.github.io/dt_portfolio/'
languageCode = 'en-us'
title = "Dustin Turpin's Portfolio"
theme = "toha"
[darkMode]
enable = true
provider = "darkreader"
default = "system"
[newsletter]
enable = false
[analytics]
enabled = false