baseURL = "https://dustinturp.github.io"
languageCode = "en-us"
title = "Dustin Turpin's Portfolio"
theme = "toha"
[darkMode]
enable = true
provider = "darkreader"
default = "system"
[params]
gitRepo = "https://github.com/dustinturp/dt_portfolio"
gitBranch = "main"
enableBlogPost = true
enableTOC = true
showFlags = true

  [params.newsletter]
  enable = true
  [params.analytics]
  enabled = false